---
- name: Ensure EPEL repo is installed
  include: epel.yml

- name: Update all packages and reboot
  include: update.yml

- name: Ensure required packages are installed
  include: yum.yml

- name: Ensure required Python packages are installed
  include: python.yml

- name: Ensure Docker is properly installed
  include: docker.yml

- name: Ensure /etc/origin/node exists
  file:
    path: /etc/origin/node
    state: directory
    recurse: yes

#- name: Ensure /etc/origin/node/resolv.conf exists
#  file:
#    path: /etc/origin/node/resolv.conf
#    state: touch

#- name: Adding node ip to /etc/resolv.conf
#  lineinfile:
#    path: /etc/resolv.conf
#    line: "nameserver {{ ansible_default_ipv4.address }}"
#
#- name: Copy resolv.conf files
#  copy:
#    src: /etc/resolv.conf
#    dest: /etc/origin/node/resolv.conf
#    remote_src: yes

- name: Ensure network interface is managed by NetworkManager
  lineinfile:
    path: /etc/selinux/config
    regexp: '^NM_CONTROLLED='
    line: 'NM_CONTROLLED=yes'
  notify: restart network
